config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # Ejemplos y documentación
  namespace :examples do
    get 'notifications', to: 'examples#notifications'
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#index"
  resources :patients
  resources :exercises
  resources :routines do
    resources :routine_exercises do
      collection do
        get :cancel
      end
    end
  end
end

app/controllers/routine_exercises_controller.rb
class RoutineExercisesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_routine
  before_action :set_routine_exercise, only: %i[destroy edit update]

  def new
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream:[
          turbo_stream.update(:add_exercise_form, partial: "routine_exercises/new_form", locals: { routine_exercise: @routine.routine_exercises.new }),
          turbo_stream.update(:add_routine_buttons, "")
        ]
      end
    end
  end

  def create
    @routine_exercise = @routine.routine_exercises.new(routine_exercise_params)
    if @routine_exercise.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream:[
            turbo_stream.append(:routine_exercises, partial: "routine_exercises/routine_exercise_card", locals: { routine_exercise: @routine_exercise }),
            turbo_stream.update(:add_exercise_form, partial: "routine_exercises/new_form", locals: { routine_exercise: @routine.routine_exercises.new })
          ]
        end
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update(:add_exercise_form, partial: "routine_exercises/new_form", locals: { routine_exercise: @routine_exercise }),
            turbo_stream.replace(:resource_errors, partial: "shared/resource_errors", locals: { resource: @routine_exercise })
          ]
        end
      end
    end
  end

  def edit
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream:[
          turbo_stream.update(:add_exercise_form, partial: "routine_exercises/edit_form", locals: { routine_exercise: @routine_exercise }),
          turbo_stream.update(:add_routine_buttons, "")
        ]
      end
    end
  end

  def update
    if @routine_exercise.update(routine_exercise_params)
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream:[
            turbo_stream.update(@routine_exercise, partial: "routine_exercises/routine_exercise_card", locals: { routine_exercise: @routine_exercise }),
            turbo_stream.update(:add_exercise_form, ""),
            turbo_stream.update(:add_routine_buttons, partial: "routine_exercises/add_routine_buttons", locals: { routine: @routine })
          ]
        end
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update(:add_exercise_form, partial: "routine_exercises/new_form", locals: { routine_exercise: @routine_exercise }),
            turbo_stream.replace(:resource_errors, partial: "shared/resource_errors", locals: { resource: @routine_exercise })
          ]
        end
      end
    end
  end

  def cancel
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update(:add_routine_buttons, partial: "routine_exercises/add_routine_buttons", locals: { routine: @routine }),
          turbo_stream.update(:add_exercise_form, "")
        ]
      end
    end
  end

  def destroy
    @routine_exercise = @routine.routine_exercises.find(params[:id])
    @routine_exercise.destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove(@routine_exercise)
      end
    end
  end

  private

  def set_routine_exercise
    @routine_exercise = @routine.routine_exercises.find(params[:id])
  end

  def set_routine
    @routine = current_clinic.routines.find(params[:routine_id])
  end


  def routine_exercise_params
    params.require(:routine_exercise).permit(
      :exercise_id, :series, :repetitions, :difficulty, :rest_time, :notes
    )
  end
end

app/helpers/routine_exercises_helper.rb
module RoutineExercisesHelper
end

app/views/routine_exercises/_add_routine_buttons.html.erb
<% if routine.pending? %>
  <%= link_to t('routines.delete_routine'), routine, data: { turbo_method: :delete, turbo_confirm: t('routines.delete_routine_confirmation', routine_name: routine.name) }, class: "bg-danger text-white font-bold py-2 px-4 rounded-xl focus:outline-none focus:shadow-outline cursor-pointer border border-danger hover:bg-background hover:text-danger mr-4" %>
<% end %>

<%= link_to t('routines.add_routine_exercise'), new_routine_routine_exercise_path(routine),  data: { turbo_stream:true }, class: "bg-secondary text-white font-bold py-2 px-4 rounded-xl focus:outline-none focus:shadow-outline cursor-pointer border border-secondary hover:bg-background hover:text-secondary" %>

app/views/routine_exercises/_edit_form.html.erb
<%= form_with(model: routine_exercise, url: routine_routine_exercise_path(routine_exercise.routine), method: :put) do |form| %>

  <div id="resource_errors">
    <%= render 'shared/resource_errors', resource: routine_exercise %>
  </div>

  <%= render 'form', form: form %>

  <div class="flex items-center justify-end">
    <%= link_to t('routines.cancel'), cancel_routine_routine_exercises_path(routine_exercise.routine), data: { turbo_stream: true }, class: "bg-gray-300 text-white font-bold py-2 px-4 rounded-xl focus:outline-none focus:shadow-outline cursor-pointer border border-gray-300 hover:bg-background hover:text-gray-100 mr-4" %>

    <%= form.submit t('routines.update'), class: "bg-accent text-white font-bold py-2 px-4 rounded-xl focus:outline-none focus:shadow-outline cursor-pointer border border-accent hover:bg-background hover:text-accent" %>
  </div>
<% end %>

app/views/routine_exercises/_form.html.erb
  <div class="flex w-full flex-wrap items-end py-3">
    <%= form.label :exercise_id, class: 'flex flex-col min-w-40 flex-1' do %>
      <p class="text-neutral-dark text-base font-medium leading-normal pb-2">
        <%= t('routines.exercise') %>
      </p>
      <%= form.select :exercise_id, Exercise.all.collect { |e| [e.name, e.id] },
        { prompt: t('routines.select_exercise') },
        class: 'form-select flex w-full min-w-0 flex-1 resize-none overflow-hidden rounded-xl text-neutral-dark focus:outline-0 focus:ring-0 border border-primary bg-slate-50 focus:border-primary h-14 p-2 text-base font-normal leading-normal bg-white'
      %>
    <% end %>
  </div>

  <div class="grid gap-4 grid-cols-3 py-3">
    <div class="flex flex-wrap items-end py-3 ">
      <%= form.label :repetitions, class: 'flex flex-col min-w-40 flex-1' do %>
        <p class="text-neutral-dark text-base font-medium leading-normal pb-2">
          <%= t('routines.repetitions') %>
        </p>
        <%= form.number_field :repetitions, class: 'form-input flex w-full min-w-0 flex-1 resize-none overflow-hidden rounded-xl text-neutral-dark focus:outline-0 focus:ring-0 border border-primary bg-slate-50 focus:border-primary h-14 placeholder:text-slate-400 p-2 text-base font-normal leading-normal bg-white' %>
      <% end %>
    </div>

    <div class="flex flex-wrap items-end py-3 ">
      <%= form.label :series, class: 'flex flex-col min-w-40 flex-1' do %>
        <p class="text-neutral-dark text-base font-medium leading-normal pb-2">
          <%= t('routines.series') %>
        </p>
        <%= form.number_field :series, class: 'form-input flex w-full min-w-0 flex-1 resize-none overflow-hidden rounded-xl text-neutral-dark focus:outline-0 focus:ring-0 border border-primary bg-slate-50 focus:border-primary h-14 placeholder:text-slate-400 p-2 text-base font-normal leading-normal bg-white' %>
      <% end %>
    </div>

    <div class="flex flex-wrap items-end py-3 ">
      <%= form.label :rest_time, class: 'flex flex-col min-w-40 flex-1' do %>
        <p class="text-neutral-dark text-base font-medium leading-normal pb-2">
          <%= t('routines.rest_time') %>
        </p>
        <%= form.number_field :rest_time, class: 'form-input flex w-full min-w-0 flex-1 resize-none overflow-hidden rounded-xl text-neutral-dark focus:outline-0 focus:ring-0 border border-primary bg-slate-50 focus:border-primary h-14 placeholder:text-slate-400 p-2 text-base font-normal leading-normal bg-white' %>
      <% end %>
    </div>
  </div>

app/views/routine_exercises/_new_form.html.erb
<%= form_with(model: routine_exercise, url: routine_routine_exercises_path(routine_exercise.routine)) do |form| %>

  <div id="resource_errors">
    <%= render 'shared/resource_errors', resource: routine_exercise %>
  </div>

  <%= render 'form', form: form %>

  <div class="flex items-center justify-end">
    <%= link_to t('routines.cancel'), cancel_routine_routine_exercises_path(routine_exercise.routine), data: { turbo_stream: true }, class: "bg-gray-300 text-white font-bold py-2 px-4 rounded-xl focus:outline-none focus:shadow-outline cursor-pointer border border-gray-300 hover:bg-background hover:text-gray-100 mr-4" %>

    <%= form.submit t('routines.submit'), class: "bg-accent text-white font-bold py-2 px-4 rounded-xl focus:outline-none focus:shadow-outline cursor-pointer border border-accent hover:bg-background hover:text-accent" %>
  </div>
<% end %>

app/views/routine_exercises/_routine_exercise_card.html.erb
<div class="max-w-sm overflow-hidden bg-white shadow-lg  rounded-xl relative" id="<%= dom_id(routine_exercise) %>">
  <div class="px-6 py-4">
    <div class="font-bold text-xl mb-2"><%= routine_exercise.exercise.name %></div>
    <p class="text-gray-700 text-base truncate">
      <%= routine_exercise.exercise.description %>
    </p>
    <p class="text-neutral-dark text-base mt-4">
      <b class="text-primary">
        <%=t('routines.series_counter', count: routine_exercise.series)%>
      </b>
      de
      <b class="text-primary">
        <%=t('routines.repetitions_counter', count: routine_exercise.repetitions)%>
      </b>
      con
      <b class="text-primary">
        <%=t('routines.rest_time_counter', count: routine_exercise.rest_time)%>
      </b>
      de descanso entre serie.
    </p>
  </div>
  <div class="px-6 py-4 ">
  </div>

  <div class="p-4 flex justify-end">
    <%= render "shared/edit_icon", path: edit_routine_routine_exercise_path(routine_exercise.routine, routine_exercise), turbo_stream: true %>
  </div>

  <%= button_to routine_routine_exercise_path(routine_exercise.routine, routine_exercise), method: :delete, data: { turbo_confirm: t('routines.delete_exercise_confirmation', exercise_name: routine_exercise.exercise.name) }, class: "absolute top-0 right-0 mt-2 mr-2 text-gray-300 hover:text-gray-800" do %>
    <svg class="h-6 w-6 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
      <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/>
    </svg>
  <% end %>
</div>

app/views/routine_exercises/new.html.erb
<div>
  <h1 class="font-bold text-4xl">RoutineExercises#new</h1>
  <p>Find me in app/views/routine_exercises/new.html.erb</p>
</div>