config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # Ejemplos y documentación
  namespace :examples do
    get 'notifications', to: 'examples#notifications'
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#index"
  resources :patients
  resources :exercises
  resources :routines do
    resources :routine_exercises do
      collection do
        get :cancel
      end
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="bg-neutral-dark text-white">
  <div class="max-w-screen-xl mx-auto px-4 py-6 md:flex justify-between items-center">
    <div class="text-sm text-gray-400">
      © <%= Time.now.year %> Todos los derechos reservados.
    </div>
    <div class="text-sm text-gray-400">
      Hecho con <span class="text-red-500">&hearts;</span> por Alejandro Prado
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="flex items-center justify-between whitespace-nowrap border-b border-solid border-l-neutral-light px-5 py-2">
  <div class="flex items-center gap-4 text-neutral-dark">
    <%= image_tag "logo.svg", alt: "Logo", class: "h-8 w-8 rounded-full" %>
    <h2 class="text-primary text-lg font-bold leading-tight">ReviseFaceApp</h2>
  </div>
  <div class="flex flex-1 justify-end gap-8">
    <button id="userMenuButton" class="focus:outline-none bg-center flex justify-center  items-center aspect-square h-10 w-10 rounded-full  text-primary">
      <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" fill="currentColor" viewBox="0 0 256 256">
        <path
          d="M230.93,220a8,8,0,0,1-6.93,4H32a8,8,0,0,1-6.92-12c15.23-26.33,38.7-45.21,66.09-54.16a72,72,0,1,1,73.66,0c27.39,8.95,50.86,27.83,66.09,54.16A8,8,0,0,1,230.93,220Z"
        ></path>
      </svg>
    </button>
  <div id="userMenu" class="hidden absolute right-0 mt-8 py-2 w-48 bg-white rounded-xl shadow-xl z-50">
    <ul>
      <li><%= link_to t('navbar.profile'), edit_user_registration_path, class: "block px-4 py-2 text-gray-800 hover:bg-gray-100" %></li>
      <li><%= link_to t('navbar.change_password'), edit_user_password_path, class: "block px-4 py-2 text-gray-800 hover:bg-gray-100" %></li>
      <li><%= link_to t('navbar.sign_out'), destroy_user_session_path, data: { turbo_method: :delete }, class: "block px-4 py-2 text-gray-800 hover:bg-gray-100" %></li>
    </ul>
  </div>
  </div>
</header>

app/views/layouts/_scripts.html.erb
<script>
  document.addEventListener('DOMContentLoaded', function() {
    const userMenuButton = document.getElementById('userMenuButton');
    const userMenu = document.getElementById('userMenu');

    userMenuButton.addEventListener('click', function() {
      userMenu.classList.toggle('hidden');
    });

    // Opcional: Cerrar el menú si se hace clic fuera de él
    document.addEventListener('click', function(event) {
      if (!userMenu.contains(event.target) && !userMenuButton.contains(event.target)) {
        userMenu.classList.add('hidden');
      }
    });
  });
</script>

app/views/layouts/_sidebar_menu.html.erb
<ul class="flex flex-col gap-2">
  <li>
    <%= link_to root_path, class: "flex items-center gap-3 px-3 py-2 rounded-xl hover:bg-[#EEEFF2] #{"bg-[#EEEFF2]" if current_page?(root_path)}" do %>
      <div class="text-neutral-dark" data-icon="House" data-size="24px" data-weight="regular">
        <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" fill="currentColor" viewBox="0 0 256 256">
          <path
            d="M218.83,103.77l-80-75.48a1.14,1.14,0,0,1-.11-.11,16,16,0,0,0-21.53,0l-.11.11L37.17,103.77A16,16,0,0,0,32,115.55V208a16,16,0,0,0,16,16H96a16,16,0,0,0,16-16V160h32v48a16,16,0,0,0,16,16h48a16,16,0,0,0,16-16V115.55A16,16,0,0,0,218.83,103.77ZM208,208H160V160a16,16,0,0,0-16-16H112a16,16,0,0,0-16,16v48H48V115.55l.11-.1L128,40l79.9,75.43.11.1Z"
          ></path>
        </svg>
      </div>
      <p class="text-neutral-dark font-medium leading-normal my-auto"><%= t('sidebar.home') %></p>
    <% end %>
  </li>
  <li>
    <%= link_to patients_path, class: "flex items-center gap-3 px-3 py-2 rounded-xl hover:bg-[#EEEFF2] #{"bg-[#EEEFF2]" if current_page?(patients_path)}" do %>
      <div class="text-neutral-dark" data-icon="House" data-size="24px" data-weight="regular">
        <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" fill="currentColor" viewBox="0 0 256 256">
          <path
            d="M117.25,157.92a60,60,0,1,0-66.5,0A95.83,95.83,0,0,0,3.53,195.63a8,8,0,1,0,13.4,8.74,80,80,0,0,1,134.14,0,8,8,0,0,0,13.4-8.74A95.83,95.83,0,0,0,117.25,157.92ZM40,108a44,44,0,1,1,44,44A44.05,44.05,0,0,1,40,108Zm210.14,98.7a8,8,0,0,1-11.07-2.33A79.83,79.83,0,0,0,172,168a8,8,0,0,1,0-16,44,44,0,1,0-16.34-84.87,8,8,0,1,1-5.94-14.85,60,60,0,0,1,55.53,105.64,95.83,95.83,0,0,1,47.22,37.71A8,8,0,0,1,250.14,206.7Z"
          ></path>
        </svg>
      </div>
      <p class="text-neutral-dark font-medium leading-normal my-auto"><%= t('sidebar.patients') %></p>
    <% end %>
  </li>
  <li>
    <%= link_to routines_path, class: "flex items-center gap-3 px-3 py-2 rounded-xl hover:bg-[#EEEFF2] #{"bg-[#EEEFF2]" if current_page?(routines_path)}" do %>
      <div class="text-neutral-dark" data-icon="House" data-size="24px" data-weight="regular">
        <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" fill="currentColor" viewBox="0 0 256 256">
          <path
            d="M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm0,192a88,88,0,1,1,88-88A88.1,88.1,0,0,1,128,216Zm64-88a8,8,0,0,1-8,8H128a8,8,0,0,1-8-8V72a8,8,0,0,1,16,0v48h48A8,8,0,0,1,192,128Z"
          ></path>
        </svg>
      </div>
      <p class="text-neutral-dark font-medium leading-normal my-auto"><%= t('sidebar.routines') %></p>
    <% end %>
  </li>
  <li>
    <%= link_to exercises_path, class: "flex items-center gap-3 px-3 py-2 rounded-xl hover:bg-[#EEEFF2] #{"bg-[#EEEFF2]" if current_page?(exercises_path)}" do %>
      <div class="text-neutral-dark" data-icon="House" data-size="24px" data-weight="regular">
        <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" fill="currentColor" viewBox="0 0 256 256">
          <path
            d="M248,120h-8V88a16,16,0,0,0-16-16H208V64a16,16,0,0,0-16-16H168a16,16,0,0,0-16,16v56H104V64A16,16,0,0,0,88,48H64A16,16,0,0,0,48,64v8H32A16,16,0,0,0,16,88v32H8a8,8,0,0,0,0,16h8v32a16,16,0,0,0,16,16H48v8a16,16,0,0,0,16,16H88a16,16,0,0,0,16-16V136h48v56a16,16,0,0,0,16,16h24a16,16,0,0,0,16-16v-8h16a16,16,0,0,0,16-16V136h8a8,8,0,0,0,0-16ZM32,168V88H48v80Zm56,24H64V64H88V192Zm104,0H168V64h24V175.82c0,.06,0,.12,0,.18s0,.12,0,.18V192Zm32-24H208V88h16Z"
          ></path>
        </svg>
      </div>
      <p class="text-neutral-dark font-medium leading-normal my-auto"><%= t('sidebar.exercises') %></p>
    <% end %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Reviceface" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= turbo_refreshes_with method: :morph, scroll: :preserve %>
    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="relative flex size-full min-h-screen flex-col bg-slate-50 group/design-root overflow-x-hidden ">
      <div class="layout-container flex h-full grow flex-col">
        <%= render 'layouts/header'%>
        <div class="layout-container flex h-full grow flex-col">
          <div class="gap-1 flex flex-1">
            <div class="layout-content-container flex flex-col w-80"> <!-- Sidebar -->
              <div class="flex h-full flex-col justify-between bg-slate-50 p-4">
                <div class="flex flex-col gap-4">
                  <%= render 'layouts/sidebar_menu' %>
                </div>
              </div>
            </div>
            <div class="layout-content-container flex flex-col flex-1"> <!-- Main content -->
              <%= render "shared/notifications" %>
              <div class="flex-grow p-5">
                <%= yield %>
              </div>
            </div>
          </div>
        </div>
        <!-- Footer -->
        <%= render 'layouts/footer' %>
      </div>
    </div>
    <%= yield :modals %>
    <%= render "layouts/scripts" %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Reviceface" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= turbo_refreshes_with method: :morph, scroll: :preserve %>
    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <div
    class="relative flex min-h-screen flex-col bg-slate-50 overflow-x-hidden">
    <main class="w-full max-w-2xl mx-auto p-5 shadow-lg bg-white rounded-lg my-auto">
      <%= yield %>
    </main>
  </div>
</body>
</html>